### ISSUE TITLE
Is `EN` pin the same as `E`?

### ISSUE THREAD

**Issue by zeenix** [levpaul/lcd1602-rs#3]
Hi, Thanks so much for putting together this crate. I'm sort of new to the world of microcontrollers so let me ask a silly question: I've a LCD 1602 that came with the SunFounder Uno starter kit . I don't want to mess things thing so my question is if [the `EN` pin](https://docs.rs/lcd1602-rs/latest/lcd1602_rs/struct.LCD1602.html#method.new) is the same as `E` pin on this [project page](https://docs.sunfounder.com/projects/uno-mega-kit/en/latest/uno/lcd1602_uno.html)?

**Comment by moritztim** [comment]
Yes. Both stand for "Enable".
